### ISSUE TITLE
while running no output given by program

### ISSUE THREAD

**Issue by venkatakrishnanagasai11** [DrMint/Email-Header-Analytics#1]
I am not getting any output in export.csv

**Comment by DrMint** [comment]
Hi, you'll have to tell me a little more about it if you want me to help.

If you uncomment line 22 in main.py, does it display the list of folders in the email account?

Also are you getting any error messages? 

Does the program ever ends? From the title of your issue, it sounds like the programe never ends. It's not suppose to run like a service.

**Comment by venkatakrishnanagasai11** [comment]
when i uncomment line 22 it gives 'mail' is not defined.
and even some classes of lib and imaplib is not working fine ithink
but when i check for the presense in package i can see that the class exists in the package
![image](https://user-images.githubusercontent.com/84707393/211499916-5b4338ef-5792-442a-874e-f116fc7bd3b3.png)

**Comment by venkatakrishnanagasai11** [comment]
![image](https://user-images.githubusercontent.com/84707393/211500161-490922fd-3651-4447-bb9a-66b9226ec0a5.png)

**Comment by DrMint** [comment]
Oh yeah my bad. I must have changed the variable name after commenting the line. You can try `server.list()`

Also be careful when sharing screenshots. I hope your email is a burner account because anyone can see the credentials.

**Comment by DrMint** [comment]
Also you should check why is the program not terminating. Is it stuck in a loop somewhere, or stuck on a command perhaps. You can try using the debugger tools and execute the program step by step.

**Comment by venkatakrishnanagasai11** [comment]
> 

yes it is a temporary account

**Comment by venkatakrishnanagasai11** [comment]
> Oh yeah my bad. I must have changed the variable name after commenting the line. You can try `server.list()`
> 
> Also be careful when sharing screenshots. I hope your email is a burner account because anyone can see the credentials.

after replacing it with server its giving about the classes
![image](https://user-images.githubusercontent.com/84707393/211505546-5fb8ddc7-2dfb-47aa-b9df-00d0e8d76924.png)

**Comment by venkatakrishnanagasai11** [comment]
and still the export.csv is empty and even classes of package lib were not included

**Comment by venkatakrishnanagasai11** [comment]
shall I install the lib package?

**Comment by DrMint** [comment]
```
from lib import *
```

is not a package that can be installed. It's just importing the functions from the other file.

What criteria have you setup? If no email correspond to the criteria, it's not surprising you get nothing in export.csv

**Comment by venkatakrishnanagasai11** [comment]
you are right i forget to ask about criteria
can you give any sample criteria?

**Comment by venkatakrishnanagasai11** [comment]
and whats this exactly mean
![Screenshot (299)](https://user-images.githubusercontent.com/84707393/211510049-fb9bb036-afa0-4c92-8a9f-ce583a377243.png)

**Comment by venkatakrishnanagasai11** [comment]
means we are using this for finding spoofed mail and filtering it right 
so what we shall mention in lines 36 to 41 means like sample format to be provided in that
